import { IStudent, IInscription, IAuditEntry, IDocument } from '@sms/shared/models';
// Class IDs match config-system (CLASSES_MAP_REF from @sms/config-system/data-access)

// ── Students ──────────────────────────────────────────────────────────────────
export const MOCK_STUDENTS: IStudent[] = [
  {
    publicId: 'stu-001', matricule: 'ML-LY-2025-CSH-07059BBA',
    firstName: 'Awa', lastName: 'Diallo',
    dateNaissance: '2007-03-15', genre: 'F',
    email: 'awa.diallo@email.com', phone: '+22312345678',
    nationalite: 'Malienne', lieuNaissance: 'Bamako', adresse: 'Hamdallaye ACI 2000', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-s1',
    classeLibelle: 'Terminale SE1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'ACTIF', dateInscription: '2025-09-03',
    parents: [
      { nom: 'Diallo Ibrahim',  relation: 'PERE', telephone: '+22300112233', email: 'ibrahim.diallo@email.com', profession: 'Ingénieur' },
      { nom: 'Koné Mariam',     relation: 'MERE', telephone: '+22300445566', email: 'mariam.kone@email.com',    profession: 'Commerçante' },
    ],
  },
  {
    publicId: 'stu-002', matricule: 'ML-LY-2025-CSH-07059BBB',
    firstName: 'Kofi', lastName: 'Mensah',
    dateNaissance: '2006-07-22', genre: 'M',
    email: 'kofi.mensah@email.com', phone: '+22356789012',
    nationalite: 'Ghanéenne', lieuNaissance: 'Accra', adresse: 'Magnambougou', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-s1',
    classeLibelle: 'Terminale SE1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'ACTIF', dateInscription: '2025-09-05',
    parents: [{ nom: 'Mensah Emmanuel', relation: 'PERE', telephone: '+2330201234567', profession: 'Médecin' }],
  },
  {
    publicId: 'stu-003', matricule: 'ML-LY-2025-CSH-07059BBC',
    firstName: 'Fatou', lastName: 'Traoré',
    dateNaissance: '2007-11-08', genre: 'F',
    email: 'fatou.traore@email.com', phone: '+22398765432',
    nationalite: 'Malienne', lieuNaissance: 'Bamako', adresse: 'Quartier du Fleuve', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-a1',
    classeLibelle: 'Terminale LL1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Lettres-Langues (LL)',
    statut: 'ACTIF', dateInscription: '2025-09-02',
    parents: [
      { nom: 'Traoré Boubacar', relation: 'PERE', telephone: '+22376123456', profession: 'Enseignant' },
      { nom: 'Sidibé Aminata',  relation: 'MERE', telephone: '+22376789012' },
    ],
  },
  {
    publicId: 'stu-004', matricule: 'ML-LY-2025-CSH-07059BBD',
    firstName: 'Moussa', lastName: 'Coulibaly',
    dateNaissance: '2006-02-14', genre: 'M',
    email: 'moussa.coulibaly@email.com', phone: '+22345678901',
    nationalite: 'Malienne', lieuNaissance: 'Ségou', adresse: 'Lafiabougou', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-a1',
    classeLibelle: 'Terminale LL1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Lettres-Langues (LL)',
    statut: 'INSCRIPTION_ANNULEE', dateInscription: '2025-09-10',
    motifStatut: 'Déménagement de la famille hors de la ville',
    parents: [{ nom: 'Coulibaly Sekou', relation: 'PERE', telephone: '+22345111222' }],
  },
  {
    publicId: 'stu-005', matricule: 'ML-LY-2025-CSH-07059BBE',
    firstName: 'Aminata', lastName: 'Koné',
    dateNaissance: '2007-09-30', genre: 'F',
    email: 'aminata.kone@email.com', phone: '+22312111222',
    nationalite: 'Malienne', lieuNaissance: 'Kayes', adresse: 'Sogoniko', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-premiere-d',
    classeLibelle: '11ème Année D', niveauLibelle: '11ème Année', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'ACTIF', dateInscription: '2025-09-01',
    parents: [
      { nom: 'Koné Adama',   relation: 'PERE', telephone: '+22312333444', profession: 'Comptable' },
      { nom: 'Diallo Kadja', relation: 'MERE', telephone: '+22312555666' },
    ],
  },
  {
    publicId: 'stu-006', matricule: 'ML-LY-2025-CSH-07059BBF',
    firstName: 'Ibrahima', lastName: 'Bah',
    dateNaissance: '2006-05-19', genre: 'M',
    email: 'ibrahima.bah@email.com', phone: '+22387654321',
    nationalite: 'Guinéenne', lieuNaissance: 'Conakry', adresse: 'Bamako-Coura', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-premiere-d',
    classeLibelle: '11ème Année D', niveauLibelle: '11ème Année', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'SUSPENDU', dateInscription: '2025-09-04',
    motifStatut: 'Absences répétées non justifiées — suspension de 15 jours',
    parents: [{ nom: 'Bah Oumar', relation: 'PERE', telephone: '+22461123456' }],
  },
  {
    publicId: 'stu-007', matricule: 'ML-LY-2025-CSH-07059BC0',
    firstName: 'Mariam', lastName: 'Sanogo',
    dateNaissance: '2007-01-25', genre: 'F',
    email: 'mariam.sanogo@email.com', phone: '+22323456789',
    nationalite: 'Malienne', lieuNaissance: 'Koutiala', adresse: 'Missira', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-s1',
    classeLibelle: 'Terminale SE1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'ACTIF', dateInscription: '2025-09-01',
    parents: [{ nom: 'Sanogo Lacina', relation: 'PERE', telephone: '+22323777888' }],
  },
  {
    publicId: 'stu-008', matricule: 'ML-LY-2025-CSH-07059BC1',
    firstName: 'Seydou', lastName: 'Ouedraogo',
    dateNaissance: '2005-12-03', genre: 'M',
    email: 'seydou.ouedraogo@email.com', phone: '+22334567890',
    nationalite: 'Burkinabè', lieuNaissance: 'Ouagadougou', adresse: 'Medina Coura', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-seconde-a',
    classeLibelle: '10ème Année A', niveauLibelle: '10ème Année', filiereLibelle: 'Sciences Humaines (SH)',
    statut: 'DIPLOME', dateInscription: '2024-09-01',
    parents: [{ nom: 'Ouedraogo Paul', relation: 'PERE', telephone: '+22670123456' }],
  },
  {
    publicId: 'stu-009', matricule: 'ML-LY-2025-CSH-07059BC2',
    firstName: 'Kadiatou', lastName: 'Camara',
    dateNaissance: '2007-06-14', genre: 'F',
    email: 'kadiatou.camara@email.com', phone: '+22345123456',
    nationalite: 'Guinéenne', lieuNaissance: 'Kankan', adresse: 'Badalabougou Est', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-a1',
    classeLibelle: 'Terminale LL1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Lettres-Langues (LL)',
    statut: 'ACTIF', dateInscription: '2025-09-03',
    parents: [
      { nom: 'Camara Fodé',   relation: 'PERE', telephone: '+22460234567' },
      { nom: 'Kouyaté Hawa',  relation: 'MERE', telephone: '+22460345678' },
    ],
  },
  {
    publicId: 'stu-010', matricule: 'ML-LY-2025-CSH-07059BD8',
    firstName: 'Ousmane', lastName: 'Diakité',
    dateNaissance: '2006-08-07', genre: 'M',
    email: 'ousmane.diakite@email.com', phone: '+22356234567',
    nationalite: 'Malienne', lieuNaissance: 'Sikasso', adresse: 'Sotuba', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-s1',
    classeLibelle: 'Terminale SE1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'PRE_INSCRIT', dateInscription: '2025-08-20',
    parents: [{ nom: 'Diakité Bourama', relation: 'PERE', telephone: '+22367890123' }],
  },
  {
    publicId: 'stu-011', matricule: 'ML-LY-2025-CSH-07059BD9',
    firstName: 'Rokhaya', lastName: 'Ndiaye',
    dateNaissance: '2007-04-22', genre: 'F',
    email: 'rokhaya.ndiaye@email.com', phone: '+22367345678',
    nationalite: 'Sénégalaise', lieuNaissance: 'Dakar', adresse: 'Quartier du Fleuve, Rue 45', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-premiere-d',
    classeLibelle: '11ème Année D', niveauLibelle: '11ème Année', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'ACTIF', dateInscription: '2025-09-01',
    parents: [
      { nom: 'Ndiaye Moussa', relation: 'PERE', telephone: '+22177123456', profession: 'Avocat' },
    ],
  },
  {
    publicId: 'stu-012', matricule: 'ML-LY-2025-CSH-07059BDA',
    firstName: 'Bakary', lastName: 'Kouyaté',
    dateNaissance: '2006-10-11', genre: 'M',
    email: 'bakary.kouyate@email.com', phone: '+22378456789',
    nationalite: 'Guinéenne', lieuNaissance: 'Labé', adresse: 'Faladié', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-a1',
    classeLibelle: 'Terminale LL1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Lettres-Langues (LL)',
    statut: 'TRANSFERE', dateInscription: '2025-09-01',
    motifStatut: 'Transfert vers Lycée Askia Mohamed de Bamako',
    parents: [{ nom: 'Kouyaté Alpha', relation: 'PERE', telephone: '+22460567890' }],
  },
  {
    publicId: 'stu-013', matricule: 'ML-LY-2025-CSH-07059BDB',
    firstName: 'Bintou', lastName: 'Keita',
    dateNaissance: '2007-07-19', genre: 'F',
    email: 'bintou.keita@email.com', phone: '+22389567890',
    nationalite: 'Malienne', lieuNaissance: 'Kayes', adresse: 'ACI 2000, Rue 320', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-seconde-a',
    classeLibelle: '10ème Année A', niveauLibelle: '10ème Année', filiereLibelle: 'Sciences Humaines (SH)',
    statut: 'INSCRIPTION_VALIDEE', dateInscription: '2025-08-25',
    parents: [{ nom: 'Keita Mamadou', relation: 'PERE', telephone: '+22367234567', profession: 'Fonctionnaire' }],
  },
  {
    publicId: 'stu-014', matricule: 'ML-LY-2025-CSH-07059BDC',
    firstName: 'Aliou', lastName: 'Barry',
    dateNaissance: '2005-03-28', genre: 'M',
    email: 'aliou.barry@email.com', phone: '+22390678901',
    nationalite: 'Guinéenne', lieuNaissance: 'Kindia', adresse: 'Kalaban Coura ACI', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-seconde-a',
    classeLibelle: '10ème Année A', niveauLibelle: '10ème Année', filiereLibelle: 'Sciences Humaines (SH)',
    statut: 'DIPLOME', dateInscription: '2024-09-01',
    parents: [{ nom: 'Barry Thierno', relation: 'PERE', telephone: '+22460789012' }],
  },
  {
    publicId: 'stu-015', matricule: 'ML-LY-2025-CSH-07059BDD',
    firstName: 'Ndeye', lastName: 'Faye',
    dateNaissance: '2007-02-05', genre: 'F',
    email: 'ndeye.faye@email.com', phone: '+22301789012',
    nationalite: 'Sénégalaise', lieuNaissance: 'Thiès', adresse: 'Hamdallaye, Rue 123', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-3eme-b',
    classeLibelle: '9ème Année B', niveauLibelle: '9ème Année Fondamentale (DEF)', filiereLibelle: 'Tronc commun',
    statut: 'ACTIF', dateInscription: '2025-09-02',
    parents: [{ nom: 'Faye Cheikh', relation: 'PERE', telephone: '+22177345678' }],
  },
  {
    publicId: 'stu-016', matricule: 'ML-LY-2025-CSH-07059BDE', firstName: 'Lamine', lastName: 'Sow',
    dateNaissance: '2006-09-16', genre: 'M', email: 'lamine.sow@email.com', phone: '+22312890123',
    nationalite: 'Sénégalaise', lieuNaissance: 'Saint-Louis', adresse: 'Missira, Extension', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-3eme-b',
    classeLibelle: '9ème Année B', niveauLibelle: '9ème Année Fondamentale (DEF)', filiereLibelle: 'Tronc commun',
    statut: 'ACTIF', dateInscription: '2025-09-01',
    parents: [{ nom: 'Sow Aliou', relation: 'PERE', telephone: '+22177456789' }],
  },
  {
    publicId: 'stu-017', matricule: 'ML-LY-2025-CSH-07059BDF', firstName: 'Aïssatou', lastName: 'Baldé',
    dateNaissance: '2007-05-31', genre: 'F', email: 'aissatou.balde@email.com', phone: '+22323901234',
    nationalite: 'Guinéenne', lieuNaissance: 'Labé', adresse: 'Sogoninko, Rue 8', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-premiere-d',
    classeLibelle: '11ème Année D', niveauLibelle: '11ème Année', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'ACTIF', dateInscription: '2025-09-01',
    parents: [{ nom: 'Baldé Cellou', relation: 'PERE', telephone: '+22460890123' }],
  },
  {
    publicId: 'stu-018', matricule: 'ML-LY-2025-CSH-07059BE0', firstName: 'Mamadou', lastName: 'Sall',
    dateNaissance: '2006-11-09', genre: 'M', email: 'mamadou.sall@email.com', phone: '+22334012345',
    nationalite: 'Sénégalaise', lieuNaissance: 'Louga', adresse: 'Bougouba', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-s1',
    classeLibelle: 'Terminale SE1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'EXCLUS', dateInscription: '2025-09-01',
    motifStatut: 'Violence physique sur un autre élève — décision du conseil de discipline',
    parents: [{ nom: 'Sall Omar', relation: 'PERE', telephone: '+22177567890' }],
  },
  {
    publicId: 'stu-019', matricule: 'ML-LY-2025-CSH-07059BE1', firstName: 'Oumou', lastName: 'Dramé',
    dateNaissance: '2007-08-24', genre: 'F', email: 'oumou.drame@email.com', phone: '+22345123987',
    nationalite: 'Malienne', lieuNaissance: 'Mopti', adresse: 'Baco Djicoroni', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-a1',
    classeLibelle: 'Terminale LL1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Lettres-Langues (LL)',
    statut: 'ACTIF', dateInscription: '2025-09-03',
    parents: [{ nom: 'Dramé Bakary', relation: 'PERE', telephone: '+22367678901' }],
  },
  {
    publicId: 'stu-020', matricule: 'ML-LY-2025-CSH-07059BF7', firstName: 'Cheikh', lastName: 'Mbaye',
    dateNaissance: '2006-01-13', genre: 'M', email: 'cheikh.mbaye@email.com', phone: '+22356234876',
    nationalite: 'Sénégalaise', lieuNaissance: 'Mbour', adresse: 'Niaréla', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-3eme-b',
    classeLibelle: '9ème Année B', niveauLibelle: '9ème Année Fondamentale (DEF)', filiereLibelle: 'Tronc commun',
    statut: 'ACTIF', dateInscription: '2025-09-02',
    parents: [{ nom: 'Mbaye Serigne', relation: 'PERE', telephone: '+22177789012' }],
  },
  {
    publicId: 'stu-021', matricule: 'ML-LY-2025-CSH-07059BF8', firstName: 'Hawa', lastName: 'Soumah',
    dateNaissance: '2007-10-02', genre: 'F', email: 'hawa.soumah@email.com', phone: '+22367345765',
    nationalite: 'Guinéenne', lieuNaissance: 'Boké', adresse: 'Kalaban Coura, Cité An II', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-seconde-a',
    classeLibelle: '10ème Année A', niveauLibelle: '10ème Année', filiereLibelle: 'Sciences Humaines (SH)',
    statut: 'INSCRIT', dateInscription: '2025-08-30',
    parents: [{ nom: 'Soumah Mohamed', relation: 'PERE', telephone: '+22460901234' }],
  },
  {
    publicId: 'stu-022', matricule: 'ML-LY-2025-CSH-07059BF9', firstName: 'Souleymane', lastName: 'Touré',
    dateNaissance: '2006-06-21', genre: 'M', email: 'souleymane.toure@email.com', phone: '+22378456654',
    nationalite: 'Guinéenne', lieuNaissance: 'Mamou', adresse: 'Lafiabougou, Cité SEMA', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-s1',
    classeLibelle: 'Terminale SE1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'ACTIF', dateInscription: '2025-09-01',
    parents: [{ nom: 'Touré Seydou', relation: 'PERE', telephone: '+22460012345' }],
  },
  {
    publicId: 'stu-023', matricule: 'ML-LY-2025-CSH-07059BFA', firstName: 'Ramata', lastName: 'Kaboré',
    dateNaissance: '2007-12-17', genre: 'F', email: 'ramata.kabore@email.com', phone: '+22389567543',
    nationalite: 'Burkinabè', lieuNaissance: 'Koudougou', adresse: 'Daoudabougou', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-a1',
    classeLibelle: 'Terminale LL1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Lettres-Langues (LL)',
    statut: 'ACTIF', dateInscription: '2025-09-04',
    parents: [{ nom: 'Kaboré Noël', relation: 'PERE', telephone: '+22670234567' }],
  },
  {
    publicId: 'stu-024', matricule: 'ML-LY-2025-CSH-07059BFB', firstName: 'Boubacar', lastName: 'Balde',
    dateNaissance: '2006-04-08', genre: 'M', email: 'boubacar.balde@email.com', phone: '+22390678432',
    nationalite: 'Guinéenne', lieuNaissance: 'Kindia', adresse: 'Sébénikoro', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-3eme-b',
    classeLibelle: '9ème Année B', niveauLibelle: '9ème Année Fondamentale (DEF)', filiereLibelle: 'Tronc commun',
    statut: 'INACTIF', dateInscription: '2025-09-01',
    parents: [{ nom: 'Balde Mamadou', relation: 'PERE', telephone: '+22460345678' }],
  },
  {
    publicId: 'stu-025', matricule: 'ML-LY-2025-CSH-07059BFC', firstName: 'Fatoumata', lastName: 'Kourouma',
    dateNaissance: '2007-03-29', genre: 'F', email: 'fatoumata.kourouma@email.com', phone: '+22301789321',
    nationalite: 'Guinéenne', lieuNaissance: 'Siguiri', adresse: 'Bamako-Coura, Rue 12', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-premiere-d',
    classeLibelle: '11ème Année D', niveauLibelle: '11ème Année', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'ACTIF', dateInscription: '2025-09-01',
    parents: [{ nom: 'Kourouma Ibrahima', relation: 'PERE', telephone: '+22460456789' }],
  },
  {
    publicId: 'stu-026', matricule: 'ML-LY-2025-CSH-07059BFD', firstName: 'Adama', lastName: 'Coulibaly',
    dateNaissance: '2006-07-14', genre: 'M', email: 'adama.coulibaly@email.com', phone: '+22312890210',
    nationalite: 'Malienne', lieuNaissance: 'Sikasso', adresse: 'Kalaban Coura', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-seconde-a',
    classeLibelle: '10ème Année A', niveauLibelle: '10ème Année', filiereLibelle: 'Sciences Humaines (SH)',
    statut: 'ACTIF', dateInscription: '2025-09-03',
    parents: [{ nom: 'Coulibaly Gaoussou', relation: 'PERE', telephone: '+22312334455' }],
  },
  {
    publicId: 'stu-027', matricule: 'ML-LY-2025-CSH-07059BFE', firstName: 'Néné', lastName: 'Sylla',
    dateNaissance: '2007-09-06', genre: 'F', email: 'nene.sylla@email.com', phone: '+22323901099',
    nationalite: 'Guinéenne', lieuNaissance: 'Kissidougou', adresse: 'Torokorobougou', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-s1',
    classeLibelle: 'Terminale SE1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'ACTIF', dateInscription: '2025-09-02',
    parents: [{ nom: 'Sylla Ibrahima', relation: 'PERE', telephone: '+22460567890' }],
  },
  {
    publicId: 'stu-028', matricule: 'ML-LY-2025-CSH-07059BFF', firstName: 'Issiaka', lastName: 'Zerbo',
    dateNaissance: '2006-12-23', genre: 'M', email: 'issiaka.zerbo@email.com', phone: '+22334012988',
    nationalite: 'Burkinabè', lieuNaissance: 'Bobo-Dioulasso', adresse: 'Bougouba, Secteur 2', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-terminale-a1',
    classeLibelle: 'Terminale LL1', niveauLibelle: 'Terminale (12ème Année)', filiereLibelle: 'Lettres-Langues (LL)',
    statut: 'ACTIF', dateInscription: '2025-09-04',
    parents: [{ nom: 'Zerbo Pascal', relation: 'PERE', telephone: '+22670345678' }],
  },
  {
    publicId: 'stu-029', matricule: 'ML-LY-2025-CSH-07059C00', firstName: 'Dieneba', lastName: 'Traoré',
    dateNaissance: '2007-02-18', genre: 'F', email: 'dieneba.traore@email.com', phone: '+22345123877',
    nationalite: 'Malienne', lieuNaissance: 'Kati', adresse: 'Djélibougou', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-3eme-b',
    classeLibelle: '9ème Année B', niveauLibelle: '9ème Année Fondamentale (DEF)', filiereLibelle: 'Tronc commun',
    statut: 'ACTIF', dateInscription: '2025-09-01',
    parents: [{ nom: 'Traoré Mamadou', relation: 'PERE', telephone: '+22367789012' }],
  },
  {
    publicId: 'stu-030', matricule: 'ML-LY-2025-CSH-07059C16', firstName: 'Tidiane', lastName: 'Diallo',
    dateNaissance: '2006-10-30', genre: 'M', email: 'tidiane.diallo@email.com', phone: '+22356234765',
    nationalite: 'Guinéenne', lieuNaissance: 'Nzérékoré', adresse: 'Banconi', ville: 'Bamako',
    etablissementId: 1, anneeAcademiqueId: 1, classePublicId: 'cls-premiere-d',
    classeLibelle: '11ème Année D', niveauLibelle: '11ème Année', filiereLibelle: 'Sciences Exactes (SE)',
    statut: 'ACTIF', dateInscription: '2025-09-02',
    parents: [{ nom: 'Diallo Thierno', relation: 'PERE', telephone: '+22460678901' }],
  },
];

// ── Inscription historique (per student) ──────────────────────────────────────
export const MOCK_INSCRIPTIONS: Record<string, IInscription[]> = {
  'stu-001': [
    { id: 'ins-001-2025', dateInscription: '2025-09-03', classePublicId: 'cls-terminale-s1', classeLibelle: 'Terminale SE1', anneeAcademique: '2025-2026', statut: 'ACTIF', typeInscription: 'RENOUVELLEMENT', responsable: 'Adm. Koné Aïcha', dateModification: '2025-09-03' },
    { id: 'ins-001-2024', dateInscription: '2024-09-02', classePublicId: 'cls-premiere-d', classeLibelle: '11ème Année D',   anneeAcademique: '2024-2025', statut: 'ACTIF', typeInscription: 'RENOUVELLEMENT', responsable: 'Adm. Koné Aïcha', dateModification: '2024-09-02' },
    { id: 'ins-001-2023', dateInscription: '2023-09-04', classePublicId: 'cls-seconde-a', classeLibelle: '10ème Année A',    anneeAcademique: '2023-2024', statut: 'ACTIF', typeInscription: 'NOUVELLE',       responsable: 'Adm. Bamba Sita',  dateModification: '2023-09-04' },
  ],
  'stu-004': [
    { id: 'ins-004-2025', dateInscription: '2025-09-10', classePublicId: 'cls-terminale-a1', classeLibelle: 'Terminale LL1', anneeAcademique: '2025-2026', statut: 'INSCRIPTION_ANNULEE', typeInscription: 'RENOUVELLEMENT', responsable: 'Adm. Koné Aïcha', dateModification: '2025-10-15', motif: 'Déménagement de la famille hors de la ville' },
    { id: 'ins-004-2024', dateInscription: '2024-09-05', classePublicId: 'cls-premiere-d', classeLibelle: '11ème Année D',   anneeAcademique: '2024-2025', statut: 'ACTIF',                typeInscription: 'RENOUVELLEMENT', responsable: 'Adm. Bamba Sita',  dateModification: '2024-09-05' },
  ],
  'stu-006': [
    { id: 'ins-006-2025', dateInscription: '2025-09-04', classePublicId: 'cls-premiere-d', classeLibelle: '11ème Année D', anneeAcademique: '2025-2026', statut: 'SUSPENDU', typeInscription: 'RENOUVELLEMENT', responsable: 'Adm. Koné Aïcha', dateModification: '2025-11-02', motif: 'Absences répétées non justifiées' },
  ],
};

// ── Audit log (per student) ───────────────────────────────────────────────────
export const MOCK_AUDIT: Record<string, IAuditEntry[]> = {
  'stu-001': [
    { id: 'aud-001-1', action: 'CREATION',       responsable: 'Adm. Bamba Sita',  date: '2023-09-04T10:32:00', details: 'Nouvelle inscription — Seconde A' },
    { id: 'aud-001-2', action: 'MODIFICATION',   responsable: 'Adm. Koné Aïcha', date: '2023-10-15T14:20:00', ancienneValeur: 'email: —', nouvelleValeur: 'email: awa.diallo@email.com', details: 'Mise à jour email' },
    { id: 'aud-001-3', action: 'CHANGEMENT_CLASSE', responsable: 'Adm. Koné Aïcha', date: '2024-09-02T09:00:00', ancienneValeur: 'Seconde A', nouvelleValeur: 'Première D', details: 'Passage en Première' },
    { id: 'aud-001-4', action: 'CHANGEMENT_CLASSE', responsable: 'Adm. Koné Aïcha', date: '2025-09-03T09:15:00', ancienneValeur: 'Première D', nouvelleValeur: 'Terminale S1', details: 'Passage en Terminale' },
  ],
  'stu-004': [
    { id: 'aud-004-1', action: 'CREATION',                  responsable: 'Adm. Bamba Sita', date: '2024-09-05T11:00:00', details: 'Nouvelle inscription — Première D' },
    { id: 'aud-004-2', action: 'CHANGEMENT_CLASSE',         responsable: 'Adm. Koné Aïcha', date: '2025-09-10T10:00:00', ancienneValeur: 'Première D', nouvelleValeur: 'Terminale A1', details: 'Passage en Terminale' },
    { id: 'aud-004-3', action: 'ANNULATION_INSCRIPTION',    responsable: 'Dir. Coulibaly',   date: '2025-10-15T16:30:00', ancienneValeur: 'ACTIF (inscrit)', nouvelleValeur: 'INSCRIPTION_ANNULEE', details: 'Déménagement famille — sur demande parentale' },
  ],
  'stu-006': [
    { id: 'aud-006-1', action: 'CREATION',    responsable: 'Adm. Bamba Sita', date: '2024-09-04T09:30:00', details: 'Nouvelle inscription' },
    { id: 'aud-006-2', action: 'SUSPENSION',  responsable: 'Dir. Coulibaly',  date: '2025-11-02T11:00:00', ancienneValeur: 'ACTIF', nouvelleValeur: 'SUSPENDU', details: '8 absences non justifiées — suspension 15 jours' },
  ],
};

// ── Documents per student ─────────────────────────────────────────────────────
export const MOCK_DOCUMENTS: Record<string, IDocument[]> = {
  'stu-001': [
    { id: 'doc-001-1', label: 'Extrait de naissance',    type: 'ACTE_NAISSANCE',    required: true,  provided: true,  dateDepot: '2023-09-04' },
    { id: 'doc-001-2', label: 'Photo d\'identité (x4)',  type: 'PHOTO',             required: true,  provided: true,  dateDepot: '2023-09-04' },
    { id: 'doc-001-3', label: 'Certificat de scolarité', type: 'CERTIFICAT_SCOLARITE', required: true, provided: true, dateDepot: '2023-09-04' },
    { id: 'doc-001-4', label: 'Carnets scolaires (x2)',  type: 'CARNET',            required: false, provided: true,  dateDepot: '2024-09-02' },
    { id: 'doc-001-5', label: 'Attestation de transfert',type: 'ATTESTATION',       required: false, provided: false  },
  ],
  'default': [
    { id: 'doc-d-1', label: 'Extrait de naissance',    type: 'ACTE_NAISSANCE',    required: true,  provided: false },
    { id: 'doc-d-2', label: 'Photo d\'identité (x4)',  type: 'PHOTO',             required: true,  provided: false },
    { id: 'doc-d-3', label: 'Certificat de scolarité', type: 'CERTIFICAT_SCOLARITE', required: true, provided: false },
    { id: 'doc-d-4', label: 'Carnets scolaires (x2)',  type: 'CARNET',            required: false, provided: false },
    { id: 'doc-d-5', label: 'Attestation de transfert',type: 'ATTESTATION',       required: false, provided: false },
  ],
};
